# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: SonarScanner.MSBuild.exe begin /k:"Krakaz_GymWebApi" /d:sonar.organization="krakaz-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="908c2828ba4b8f880ff280677f96fc59480265e1"
  displayName: 'SonarScanner'